[phases.setup]
providers = ["csharp"]

[phases.install]
cmds = ["cd SalaryManagement.Web && dotnet restore"]

[phases.build]
cmds = ["cd SalaryManagement.Web && dotnet publish -c Release -o /app/publish"]

[start]
cmd = "dotnet /app/publish/SalaryManagement.Web.dll"