[phases.setup]
nixPkgs = ["dotnet-sdk_10"]

[phases.build]
cmds = ["dotnet publish SalaryManagement.Web/SalaryManagement.Web.csproj -c Release -o out"]

[start]
cmd = "dotnet out/SalaryManagement.Web.dll"
