// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalaryManagement.Infrastructure.Data;

#nullable disable

namespace SalaryManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalaryManagement.Domain.Entities.BangLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaoHiemThatNghiep")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaoHiemXaHoi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaoHiemYTe")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BhTnCongTy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BhXhCongTy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BhYtCongTy")
                        .HasColumnType("numeric");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<decimal>("GiamTruBanThan")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GiamTruNguoiPhuThuoc")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LuongLamThem")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LuongTheoNgayCong")
                        .HasColumnType("numeric");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiDuyet")
                        .HasColumnType("text");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PhuCapAnTrua")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhuCapDienThoai")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhuCapNhaO")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhuCapTrachNhiem")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhuCapXangXe")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SoGioLamThem")
                        .HasColumnType("numeric");

                    b.Property<int>("SoNgayCongChuan")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoNgayCongThucTe")
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThuNhapChiuThue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ThuNhapRong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThueThuNhapCaNhan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongChiPhiCongTy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TongPhat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TongThuNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongThuong")
                        .HasColumnType("numeric");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId", "Thang", "Nam")
                        .IsUnique();

                    b.ToTable("BangLuongs");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.CauHinhHeThong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PhuCapAnTruaMoiNgay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhuCapXangXeMoiNgay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CauHinhHeThongs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaXoa = false,
                            GhiChu = "Cấu hình mặc định",
                            NgayHieuLuc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PhuCapAnTruaMoiNgay = 30000m,
                            PhuCapXangXeMoiNgay = 20000m
                        });
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.CauHinhLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PhuCapAnTrua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhuCapDienThoai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhuCapNhaO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhuCapTrachNhiem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhuCapXangXe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoNgayCongChuan")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId")
                        .IsUnique();

                    b.ToTable("CauHinhLuongs");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.ChamCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoGioTangCa")
                        .HasColumnType("numeric");

                    b.Property<int>("SoNgayLamViec")
                        .HasColumnType("integer");

                    b.Property<int>("SoNgayNghi")
                        .HasColumnType("integer");

                    b.Property<int>("SoNgayNghiPhep")
                        .HasColumnType("integer");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId", "Thang", "Nam")
                        .IsUnique();

                    b.ToTable("ChamCongs");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.ChucVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CapBac")
                        .HasColumnType("integer");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LuongToiDa")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LuongToiThieu")
                        .HasColumnType("numeric");

                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PhuCapDienThoai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhuCapNhaO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhuCapTrachNhiem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChucVus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapBac = 10,
                            DaXoa = false,
                            LuongToiDa = 200000000m,
                            LuongToiThieu = 50000000m,
                            MaChucVu = "CEO",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PhuCapDienThoai = 500000m,
                            PhuCapNhaO = 1000000m,
                            PhuCapTrachNhiem = 2000000m,
                            TenChucVu = "Giám đốc"
                        },
                        new
                        {
                            Id = 2,
                            CapBac = 7,
                            DaXoa = false,
                            LuongToiDa = 50000000m,
                            LuongToiThieu = 20000000m,
                            MaChucVu = "MGR",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PhuCapDienThoai = 300000m,
                            PhuCapNhaO = 500000m,
                            PhuCapTrachNhiem = 1000000m,
                            TenChucVu = "Trưởng phòng"
                        });
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text");

                    b.Property<int>("ChucVuId")
                        .HasColumnType("integer");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<string>("DienThoai")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LaCuTru")
                        .HasColumnType("boolean");

                    b.Property<string>("MaBHXH")
                        .HasColumnType("text");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayNghiViec")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PhongBanId")
                        .HasColumnType("integer");

                    b.Property<string>("SoCMND")
                        .HasColumnType("text");

                    b.Property<int>("SoNguoiPhuThuoc")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<int>("Vung")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChucVuId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaNhanVien")
                        .IsUnique();

                    b.HasIndex("PhongBanId");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.PhongBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<string>("MaPhongBan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TruongPhongId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PhongBans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaXoa = false,
                            MaPhongBan = "IT",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenPhongBan = "Phòng Công nghệ Thông tin"
                        },
                        new
                        {
                            Id = 2,
                            DaXoa = false,
                            MaPhongBan = "HR",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenPhongBan = "Phòng Nhân sự"
                        });
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NhanVienId")
                        .HasColumnType("integer");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaXoa = false,
                            MatKhau = "admin123",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDangNhap = "admin",
                            VaiTro = "Admin"
                        });
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.ThuongPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BangLuongId")
                        .HasColumnType("integer");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<int>("Loai")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiDuyet")
                        .HasColumnType("text");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("numeric");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BangLuongId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("ThuongPhats");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.BangLuong", b =>
                {
                    b.HasOne("SalaryManagement.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("BangLuongs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.CauHinhLuong", b =>
                {
                    b.HasOne("SalaryManagement.Domain.Entities.NhanVien", "NhanVien")
                        .WithOne("CauHinhLuong")
                        .HasForeignKey("SalaryManagement.Domain.Entities.CauHinhLuong", "NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.ChamCong", b =>
                {
                    b.HasOne("SalaryManagement.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.NhanVien", b =>
                {
                    b.HasOne("SalaryManagement.Domain.Entities.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("ChucVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalaryManagement.Domain.Entities.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.TaiKhoan", b =>
                {
                    b.HasOne("SalaryManagement.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.ThuongPhat", b =>
                {
                    b.HasOne("SalaryManagement.Domain.Entities.BangLuong", "BangLuong")
                        .WithMany("ThuongPhats")
                        .HasForeignKey("BangLuongId");

                    b.HasOne("SalaryManagement.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BangLuong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.BangLuong", b =>
                {
                    b.Navigation("ThuongPhats");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.NhanVien", b =>
                {
                    b.Navigation("BangLuongs");

                    b.Navigation("CauHinhLuong");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
